name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    # every 2 hours
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Token
        id: get_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: "${{ secrets.RENOVATE_APPLICATION_ID }}"
          application_private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.13
        with:
          token: ${{ steps.get_token.outputs.token }}
          configurationFile: renovate-config.json
